import logging
import os
import string
import sys
import textwrap
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
from matplotlib import ticker
from matplotlib.lines import Line2D

# Add parent directory to path so we can import utils and plotting_utils
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from avoided_change_analysis import run_avoided_change_analysis

import plotting_utils
import utils

logger = logging.getLogger(__name__)


def generate_figure_7(
    ds_tsi: xr.Dataset | None = None,
    vars_include: list[str] | None = None,
    output_dir: Path | None = None,
    file_format: str | None = None,
    variants_to_exclude: list[str] | None = plotting_utils.fig_params.get(
        "perm_variants"
    ),
    end_year: int | None = None,
    csv_path: Path | None = None,
) -> None:
    """
    Generates and saves Figure 7 of the paper (Relative Avoided Change).

    This figure shows:
      - Relative avoided change for each variant/scenario at years 2100 and 2300,
        expressed as a percentage relative to the baseline.
      - Uses a logarithmic scale (symlog) to display differences clearly.

    Instead of calculating values inline, this script reads data from a pre-calculated
    CSV file generated by avoided_change_analysis.py.

    Parameters
    ----------
    ds_tsi : xr.Dataset, optional
        The main timeseries dataset. If not provided, it will be loaded from the default path.
    vars_include : list of str, optional
        Variables to represent the colums
    output_dir : Path, optional
        Directory where the figure will be saved. Defaults to utils.FIGURE_DIR.
    file_format : str, optional
        Format of the output file (e.g., 'pdf', 'png'). Defaults to fig_params['file_format'].
    variants_to_exclude : list of str, optional
        List of variants to exclude from plotting. Defaults to permanent variants.
    end_year : int, optional
        The end year for plotting. Defaults to the maximum year in the dataset.
    csv_path : Path, optional
        Path to the pre-calculated CSV containing relative avoided change results.
        If it does not exist, it will be generated automatically.
    """
    logger.info("Plotting Figure 7...")

    # Load configuration parameters
    fig_params = plotting_utils.fig_params
    colours = fig_params["colours"]
    plot_config = fig_params["plot_config"]

    l_font = plot_config.get("label_fontsize", 11)
    t_font = plot_config.get("subplot_title_fontsize", 12)
    leg_font = plot_config.get("legend_fontsize", 11) - 2
    e_col = plot_config.get("legend_edge_color", "black")

    # Load dataset if not provided
    if ds_tsi is None:
        try:
            ds_tsi, _ = utils.load_main_datasets()
        except FileNotFoundError as e:
            logger.error(
                f"Required data not found. Ensure files are in the data directory. {e}"
            )
            raise

    # Load vars_include from utils if not provided
    if vars_include is None:
        vars_include = getattr(utils, "vars_irrev", [])

    # Resolve output directory, file format, and resolution
    if output_dir is None:
        output_dir = utils.FIGURE_DIR
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if file_format is None:
        file_format = fig_params.get("file_format", "pdf")
    fig_dpi = fig_params.get("fig_dpi", 300)

    # Resolve CSV path
    if csv_path is None:
        csv_path = utils.OUTPUT_DIR / "avoided_change_results.csv"
    csv_path = Path(csv_path)

    # Automatically generate analysis CSV if it is missing
    if not csv_path.exists():
        logger.info(f"{csv_path} not found. Running avoided change analysis first...")
        run_avoided_change_analysis(ds_tsi=ds_tsi, output_dir=csv_path.parent)

    years = ds_tsi.time.values
    if max(years) < 2300:
        logger.warning(
            "Dataset time range is less than 2300. Figure 7 requires data up to 2300."
        )
        return

    # Sort scenarios using the canonical order defined in utils
    scenarios_to_plot = utils._sort_ssp(ds_tsi.scenario.values)
    _, patch_handles = plotting_utils.get_plot_elements(
        ds_tsi, ["base"], scenarios_to_plot
    )
    patch_handles = utils._sort_ssp(patch_handles)

    # Resolve active variants to plot
    active_variants = [
        v
        for v in ds_tsi.variant.values
        if v not in (variants_to_exclude or []) and v != "base"
    ]

    # Map each variant to a marker
    all_variants_no_base = [v for v in fig_params["temp_variants"] if v != "base"]
    markers = ["o", "s", "v", "^", "D", "*", "1", "3", "x"]
    marker_map = {v: m for v, m in zip(all_variants_no_base, markers)}

    # Read pre-calculated results from the CSV
    logger.info(f"Loading data from {csv_path}...")
    df = pd.read_csv(csv_path)

    # Reconstruct the results structure in the SSP order
    results = {}
    for yr in [2100.5, 2300.5]:
        yr_int = int(yr)
        results[yr] = {}
        for var in vars_include:
            results[yr][var] = {}
            for v_n in active_variants:
                df_sub = df[(df["year"] == yr_int) & (df["variable"] == var)]
                df_sub = df_sub.set_index("scenario").reindex(scenarios_to_plot)
                results[yr][var][v_n] = df_sub[v_n].tolist()

    fig, axs = plt.subplots(2, 1, figsize=(9, 10), sharex=True)
    ssp_colors = [colours[ssp] for ssp in scenarios_to_plot]

    # --- Plotting Loop ---
    for i, yr in enumerate([2100.5, 2300.5]):
        ax = axs[i]

        # Set grid for log scale to help orientation
        ax.grid(True, which="both", axis="y", ls="-", alpha=0.1)
        ax.axhline(0, color="black", lw=1.2, zorder=2)

        for x_idx, var in enumerate(vars_include):
            # Jittering to avoid point overlap within each variable column
            jx = np.linspace(x_idx - 0.3, x_idx + 0.3, num=len(scenarios_to_plot))

            for v_n in active_variants:
                z_val = 20
                # Outlines only for removal variants
                lw_val = 0

                ax.scatter(
                    jx,
                    results[yr][var][v_n],
                    c=ssp_colors,
                    marker=marker_map[v_n],
                    s=65,
                    alpha=0.75,
                    zorder=z_val,
                    linewidths=lw_val,
                    edgecolors="black",
                )

        ax.set_title(f"Year {int(yr)}", fontsize=t_font, fontweight="bold")
        ax.set_ylabel("Avoided change relative\nto baseline (%)", fontsize=l_font)

        # Custom formatter for percentage labels on log scale
        ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f"{x:g}%"))

        ax.text(
            -0.1,
            1.05,
            f"{string.ascii_uppercase[i]})",
            transform=ax.transAxes,
            fontsize=t_font,
            fontweight="bold",
            va="top",
        )

    # First plot using linear scale as configured in the original script
    # to maintain compatibility before applying logarithmic scale
    axs[0].set_ylim(0, 24)
    axs[1].set_ylim(-15, 20)

    var_labs = [
        "\n".join(
            textwrap.wrap(ds_tsi[v].attrs.get("long_name", v).capitalize(), width=15)
        )
        for v in vars_include
    ]
    axs[1].set_xticks(range(len(vars_include)))
    axs[1].set_xticklabels(var_labs, fontsize=l_font - 1)

    # Scenario legend
    axs[0].legend(
        handles=patch_handles,
        loc="upper right",
        bbox_to_anchor=(1, 1),
        ncol=3,
        frameon=True,
        edgecolor=e_col,
        fontsize=leg_font,
    )
    axs[0].add_artist(axs[0].get_legend())

    # Variant legend
    sh = []
    for v in active_variants:
        prefix = "Removal" if v in ["sce7", "sce8", "sce9"] else "Storage"
        lw_leg = 0
        sh.append(
            Line2D(
                [0],
                [0],
                marker=marker_map[v],
                color="black",
                linestyle="None",
                label=f"{prefix} {v[-1]}",
                markersize=8,
                markeredgewidth=lw_leg,
                markeredgecolor="black" if lw_leg > 0 else "none",
            )
        )

    axs[0].legend(
        handles=sh,
        loc="upper left",
        bbox_to_anchor=(0, 1),
        frameon=True,
        edgecolor=e_col,
        ncol=3,
        fontsize=leg_font,
    )

    # Save original linear version
    output_path_linear = output_dir / f"figure7.{file_format}"
    plt.savefig(
        output_path_linear,
        dpi=fig_dpi,
        bbox_inches="tight",
    )

    # --- LOG SCALE CONFIGURATION ---
    # Using symlog to handle the 0 baseline. linthresh=1.0 keeps 0-1% linear.
    for ax in axs:
        ax.set_yscale("symlog")
        ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f"{x:g}%"))

    # Adjust limits to ensure everything is visible in symlog space
    axs[0].set_ylim(0, 150)
    axs[1].set_ylim(-50, 150)

    # Save symlog version
    output_path_symlog = output_dir / f"figure7_symlog.{file_format}"
    plt.savefig(
        output_path_symlog,
        dpi=fig_dpi,
        bbox_inches="tight",
    )
    plt.close()
    logger.info(f"Figure successfully saved to {output_path_symlog}")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )
    # Ensure directories are set up prior to running
    utils.setup_output_directories()
    generate_figure_7()
